import { ArrowLeft, ShieldCheck } from "lucide-react";
import { Link, useRoute } from "wouter";

type PageKey = "privacy" | "terms" | "disclaimer" | "support";
const content: Record<PageKey, { eyebrow: string; title: string; paragraphs: string[]; sections: [string, string][] }> = {
  privacy: { eyebrow: "Privacy policy", title: "Your safety data should stay understandable and controlled.", paragraphs: ["SurakshaShe stores the information needed to provide the safety workspace: account details, trusted contacts, safety check-ins, SOS incidents, notification records, and location data captured when you request a location or activate an SOS."], sections: [["What we collect", "Account identity, contact details you choose to save, incident coordinates and accuracy, timestamps, notification outcomes, acknowledgements, and audit events needed to protect the service."], ["Your controls", "You can export your data, delete SOS history, delete your account, revoke emergency links by marking yourself safe, and remove trusted contacts from the workspace."], ["What we do not claim", "Browser offline mode does not deliver SOS messages without network access. Browser location does not provide continuous background tracking after the page is closed."], ["Provider sharing", "If you configure email, SMS, or WhatsApp providers, the selected contact details and message content are sent to that provider to perform the requested notification. Keep provider credentials in server-side secrets."]] },
  terms: { eyebrow: "Terms of service", title: "Use SurakshaShe as a planning and assistance tool.", paragraphs: ["By using SurakshaShe, you agree to provide accurate information, protect your account, and use the service lawfully. You are responsible for choosing trusted contacts and confirming that you have permission to contact them."], sections: [["No guaranteed response", "SurakshaShe does not guarantee that a message will be delivered, read, or answered. A provider status of sent means accepted by that provider, not confirmed human response."], ["Emergency services", "For immediate danger, contact local emergency services. In India, the visible emergency option is 112. Do not wait for a web application to respond."], ["Account safety", "Do not share passwords, reset links, emergency tokens, or trusted-contact information publicly. Report suspected unauthorized access through Support."]] },
  disclaimer: { eyebrow: "Emergency disclaimer", title: "If you are in immediate danger, call emergency services now.", paragraphs: ["SurakshaShe is not police, ambulance, fire dispatch, a medical service, or a guaranteed emergency-response network. It is a personal safety workspace that can help organize information and attempt configured notifications."], sections: [["Call 112 in India", "Use the prominent 112 option for India’s nationwide emergency response number. Also use the emergency number appropriate to your location."], ["Technology limits", "Location permissions, network connectivity, browser restrictions, provider outages, incorrect contact details, and device power can prevent or delay a notification."], ["Safe use", "Keep the app open for browser live-location updates, test your trusted-contact plan before relying on it, and never use the fake-call feature as a substitute for contacting emergency services."]] },
  support: { eyebrow: "Support and contact", title: "Need help understanding the safety workspace?", paragraphs: ["For account, privacy, provider-configuration, or security questions, contact the project support owner using the configured support address. Do not email passwords, reset tokens, emergency tokens, or private location history."], sections: [["Before contacting support", "Include the page or feature where the issue occurred, approximate time, browser/device type, and a short description. Remove personal phone numbers, addresses, and tokens."], ["Provider setup", "Real SMS, email, and WhatsApp delivery require verified provider accounts and server-side secrets. The product intentionally shows a failed or not-configured state instead of pretending a message was delivered."], ["Emergency help", "Support is not monitored as an emergency dispatch channel. Call 112 in India or the appropriate local emergency service for immediate danger."]] },
};

export default function TrustPage() {
  const [, params] = useRoute("/:page");
  const key = (params?.page || "privacy") as PageKey;
  const page = content[key] || content.privacy;
  return <main className="min-h-screen bg-[#fbf8f7] text-slate-900"><header className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-4xl items-center justify-between px-5 py-5 sm:px-8"><Link href="/welcome" className="inline-flex items-center gap-2 text-sm font-bold text-slate-600 hover:text-slate-950"><ArrowLeft size={16} /> SurakshaShe</Link><ShieldCheck className="text-rose-600" size={24} /></div></header><article className="mx-auto max-w-4xl px-5 py-14 sm:px-8"><p className="text-xs font-bold uppercase tracking-[0.18em] text-rose-600">{page.eyebrow}</p><h1 className="mt-4 max-w-3xl font-display text-4xl font-semibold tracking-tight text-slate-950 sm:text-5xl">{page.title}</h1>{page.paragraphs.map((paragraph) => <p key={paragraph} className="mt-6 max-w-3xl text-lg leading-8 text-slate-600">{paragraph}</p>)}<div className="mt-12 grid gap-5 md:grid-cols-2">{page.sections.map(([title, text]) => <section key={title} className="rounded-3xl border border-slate-200 bg-white p-6"><h2 className="font-semibold text-slate-950">{title}</h2><p className="mt-3 text-sm leading-7 text-slate-600">{text}</p></section>)}</div>{key === "support" && <p className="mt-10 rounded-2xl border border-slate-200 bg-white px-5 py-4 text-sm leading-6 text-slate-600">The deployment owner should configure `SUPPORT_EMAIL` in the project environment before publishing a support mailbox.</p>}</article></main>;
}
